// Package compiler implements the Liquid AOT template compiler. It pairs
// .lsx templates with their component source files by filename convention
// (user_card.lsx ↔ user_card.go defining UserCard) and emits html/template
// markup as *_gen.go files beside the source.
package compiler

import (
	"fmt"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/net/html"
	"golang.org/x/net/html/atom"
)

// Build compiles every .lsx file under dir, writing a <name>_gen.go file
// beside each one containing the paired component's Template method.
func Build(dir string) error {
	var lsxFiles []string
	err := filepath.WalkDir(dir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() && strings.HasSuffix(path, ".lsx") {
			lsxFiles = append(lsxFiles, path)
		}
		return nil
	})
	if err != nil {
		return fmt.Errorf("scanning %s for .lsx files: %w", dir, err)
	}

	for _, path := range lsxFiles {
		if err := compileFile(path); err != nil {
			return fmt.Errorf("compiling %s: %w", path, err)
		}
	}
	return nil
}

// compileFile compiles one .lsx file and writes its paired *_gen.go.
func compileFile(lsxPath string) error {
	base := strings.TrimSuffix(lsxPath, ".lsx")
	goPath := base + ".go"

	pkg, err := packageName(goPath)
	if err != nil {
		return fmt.Errorf("resolving paired source %s: %w", goPath, err)
	}

	src, err := os.ReadFile(lsxPath)
	if err != nil {
		return fmt.Errorf("reading template: %w", err)
	}

	compiled, err := compileLSX(src)
	if err != nil {
		return err
	}

	structName := pascalCase(filepath.Base(base))
	generated := fmt.Sprintf(`// Code generated by liquid build; DO NOT EDIT.

package %s

// Template returns the compiled .lsx markup for %s.
func (c *%s) Template() string {
	return %q
}
`, pkg, structName, structName, compiled)

	formatted, err := format.Source([]byte(generated))
	if err != nil {
		return fmt.Errorf("formatting generated code: %w", err)
	}

	genPath := base + "_gen.go"
	if err := os.WriteFile(genPath, formatted, 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", genPath, err)
	}
	return nil
}

// compileLSX parses .lsx markup into an HTML node tree, applies the template
// transforms, and renders the result as html/template text.
func compileLSX(src []byte) (string, error) {
	ctx := &html.Node{Type: html.ElementNode, Data: "body", DataAtom: atom.Body}
	nodes, err := html.ParseFragment(strings.NewReader(string(src)), ctx)
	if err != nil {
		return "", fmt.Errorf("parsing .lsx markup: %w", err)
	}

	var b strings.Builder
	for _, n := range nodes {
		transform(n)
		if err := html.Render(&b, n); err != nil {
			return "", fmt.Errorf("rendering compiled template: %w", err)
		}
	}
	return strings.TrimRight(b.String(), "\n"), nil
}

// transform rewrites Liquid template sugar on a parsed node and its children.
func transform(n *html.Node) {
	if n.Type == html.TextNode {
		n.Data = rewriteInterpolations(n.Data)
	}
	for i := range n.Attr {
		n.Attr[i].Val = rewriteInterpolations(n.Attr[i].Val)
	}
	for c := n.FirstChild; c != nil; c = c.NextSibling {
		transform(c)
	}
}

// rewriteInterpolations turns each {{ Field }} occurrence into the
// html/template form {{ .Field }}. Expressions already rooted at a dot are
// left untouched.
func rewriteInterpolations(s string) string {
	var b strings.Builder
	for {
		start := strings.Index(s, "{{")
		if start < 0 {
			b.WriteString(s)
			return b.String()
		}
		end := strings.Index(s[start:], "}}")
		if end < 0 {
			b.WriteString(s)
			return b.String()
		}
		end += start
		inner := strings.TrimSpace(s[start+2 : end])
		b.WriteString(s[:start])
		if inner != "" && !strings.HasPrefix(inner, ".") {
			inner = "." + inner
		}
		b.WriteString("{{ " + inner + " }}")
		s = s[end+2:]
	}
}

// packageName reads the package clause of the paired .go source file.
func packageName(goPath string) (string, error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, goPath, nil, parser.PackageClauseOnly)
	if err != nil {
		return "", fmt.Errorf("parsing package clause: %w", err)
	}
	return f.Name.Name, nil
}

// pascalCase converts a snake_case file base name to the PascalCase struct
// name it pairs with (user_card → UserCard).
func pascalCase(s string) string {
	parts := strings.Split(s, "_")
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]) + p[1:])
	}
	return b.String()
}
