// Package compiler implements the Liquid AOT template compiler. It pairs
// .lsx templates with their component source files by filename convention
// (user_card.lsx ↔ user_card.go defining UserCard) and emits html/template
// markup as *_gen.go files beside the source.
package compiler

import (
	"context"
	"errors"
	"fmt"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/net/html"
	"golang.org/x/net/html/atom"
)

// Build compiles every .lsx file under dir, writing a <name>_gen.go file
// beside each one containing the paired component's Template method. Problems
// in the input the user can fix come back as diagnostics (no generated file is
// written for a .lsx with an error diagnostic); the error covers mechanical
// failures such as unreadable directories.
func Build(ctx context.Context, dir string) ([]Diagnostic, error) {
	return eachLSX(dir, func(path string) ([]Diagnostic, error) {
		return compileFile(ctx, path)
	})
}

// Vet runs the same diagnostic checks as Build on every .lsx file under dir
// without writing any generated files (D13).
func Vet(ctx context.Context, dir string) ([]Diagnostic, error) {
	return eachLSX(dir, func(path string) ([]Diagnostic, error) {
		diags, _, err := analyzeFile(ctx, path)
		return diags, err
	})
}

// eachLSX applies fn to every .lsx file under dir, collecting diagnostics.
func eachLSX(dir string, fn func(path string) ([]Diagnostic, error)) ([]Diagnostic, error) {
	var lsxFiles []string
	err := filepath.WalkDir(dir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() && strings.HasSuffix(path, ".lsx") {
			lsxFiles = append(lsxFiles, path)
		}
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("scanning %s for .lsx files: %w", dir, err)
	}

	var diags []Diagnostic
	for _, path := range lsxFiles {
		ds, err := fn(path)
		if err != nil {
			return nil, fmt.Errorf("checking %s: %w", path, err)
		}
		diags = append(diags, ds...)
	}
	return diags, nil
}

// analyzeFile runs the diagnostic checks for one .lsx file: the pairing
// convention (LSX002), interpolation syntax (LSX001), and the go/types
// reference cross-check (LSX003, LSX004). It returns the raw template source
// so compileFile can reuse it without a second read.
func analyzeFile(ctx context.Context, lsxPath string) ([]Diagnostic, []byte, error) {
	base := strings.TrimSuffix(lsxPath, ".lsx")
	goPath := base + ".go"
	structName := pascalCase(filepath.Base(base))

	if _, err := os.Stat(goPath); errors.Is(err, fs.ErrNotExist) {
		return []Diagnostic{{
			File:     lsxPath,
			Line:     1,
			Col:      1,
			Severity: SeverityError,
			Code:     CodeMissingPairedSource,
			Message: fmt.Sprintf("no paired Go source file for %s: %s does not exist",
				filepath.Base(lsxPath), filepath.Base(goPath)),
			Suggestion: fmt.Sprintf("create %s defining a struct named %s",
				filepath.Base(goPath), structName),
		}}, nil, nil
	}

	src, err := os.ReadFile(lsxPath)
	if err != nil {
		return nil, nil, fmt.Errorf("reading template: %w", err)
	}

	interps, diags := scanInterpolations(lsxPath, src)
	if len(diags) > 0 {
		return diags, nil, nil
	}

	vetDiags, err := vetReferences(ctx, filepath.Dir(lsxPath), lsxPath, structName, interps)
	if err != nil {
		return nil, nil, fmt.Errorf("vetting: %w", err)
	}
	return vetDiags, src, nil
}

// compileFile compiles one .lsx file and writes its paired *_gen.go, unless
// the file has diagnostics, which it returns instead.
func compileFile(ctx context.Context, lsxPath string) ([]Diagnostic, error) {
	diags, src, err := analyzeFile(ctx, lsxPath)
	if err != nil {
		return nil, err
	}
	if len(diags) > 0 {
		return diags, nil
	}

	base := strings.TrimSuffix(lsxPath, ".lsx")
	structName := pascalCase(filepath.Base(base))

	pkg, err := packageName(base + ".go")
	if err != nil {
		return nil, fmt.Errorf("resolving paired source %s: %w", base+".go", err)
	}

	compiled, err := compileLSX(src)
	if err != nil {
		return nil, err
	}

	generated := fmt.Sprintf(`// Code generated by liquid build; DO NOT EDIT.

package %s

// Template returns the compiled .lsx markup for %s.
func (c *%s) Template() string {
	return %q
}
`, pkg, structName, structName, compiled)

	formatted, err := format.Source([]byte(generated))
	if err != nil {
		return nil, fmt.Errorf("formatting generated code: %w", err)
	}

	genPath := base + "_gen.go"
	if err := os.WriteFile(genPath, formatted, 0o644); err != nil {
		return nil, fmt.Errorf("writing %s: %w", genPath, err)
	}
	return nil, nil
}

// compileLSX parses .lsx markup into an HTML node tree, applies the template
// transforms, and renders the result as html/template text.
func compileLSX(src []byte) (string, error) {
	ctx := &html.Node{Type: html.ElementNode, Data: "body", DataAtom: atom.Body}
	nodes, err := html.ParseFragment(strings.NewReader(string(src)), ctx)
	if err != nil {
		return "", fmt.Errorf("parsing .lsx markup: %w", err)
	}

	var b strings.Builder
	for _, n := range nodes {
		transform(n)
		if err := html.Render(&b, n); err != nil {
			return "", fmt.Errorf("rendering compiled template: %w", err)
		}
	}
	return strings.TrimRight(b.String(), "\n"), nil
}

// transform rewrites Liquid template sugar on a parsed node and its children.
func transform(n *html.Node) {
	if n.Type == html.TextNode {
		n.Data = rewriteInterpolations(n.Data)
	}
	for i := range n.Attr {
		n.Attr[i].Val = rewriteInterpolations(n.Attr[i].Val)
	}
	for c := n.FirstChild; c != nil; c = c.NextSibling {
		transform(c)
	}
}

// rewriteInterpolations turns each {{ Field }} occurrence into the
// html/template form {{ .Field }}. Expressions already rooted at a dot are
// left untouched.
func rewriteInterpolations(s string) string {
	var b strings.Builder
	for {
		start := strings.Index(s, "{{")
		if start < 0 {
			b.WriteString(s)
			return b.String()
		}
		end := strings.Index(s[start:], "}}")
		if end < 0 {
			b.WriteString(s)
			return b.String()
		}
		end += start
		inner := strings.TrimSpace(s[start+2 : end])
		b.WriteString(s[:start])
		if inner != "" && !strings.HasPrefix(inner, ".") {
			inner = "." + inner
		}
		b.WriteString("{{ " + inner + " }}")
		s = s[end+2:]
	}
}

// packageName reads the package clause of the paired .go source file.
func packageName(goPath string) (string, error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, goPath, nil, parser.PackageClauseOnly)
	if err != nil {
		return "", fmt.Errorf("parsing package clause: %w", err)
	}
	return f.Name.Name, nil
}

// pascalCase converts a snake_case file base name to the PascalCase struct
// name it pairs with (user_card → UserCard).
func pascalCase(s string) string {
	parts := strings.Split(s, "_")
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]) + p[1:])
	}
	return b.String()
}
