// Code generated by liquid build; DO NOT EDIT.

package ui

// Template returns the compiled .lsx markup for Admin.
func (c *Admin) Template() string {
	return "<main class=\"admin\">\n  <h1>Admin area</h1>\n  <p>You presented the right key, so the guard let you through.</p>\n  <p><a href=\"/\">Back to the dashboard</a></p>\n</main>"
}
