// Code generated by liquid build; DO NOT EDIT.

package ui

// Template returns the compiled .lsx markup for Chart.
func (c *Chart) Template() string {
	return "<section data-hydro-id=\"{{ .HydroID }}\" id=\"chart\" class=\"card glass card--wide\">\n  <div class=\"card__head\">\n    <span class=\"card__icon card__icon--chart\">\n      <svg viewBox=\"0 0 24 24\" fill=\"currentColor\" aria-hidden=\"true\"><path d=\"M3 3h2v16h16v2H3zm4 10 4-4 3 3 5-6 1.4 1.3-6.4 7.4-3-3-2.6 2.6z\"></path></svg>\n    </span>\n    <h2 class=\"card__title\">Portfolio value</h2>\n    <span class=\"live-dot\" aria-hidden=\"true\"></span>\n  </div>\n  <p class=\"metric-value\">\n    <span id=\"chart-last\">{{ .Last }}</span>\n    <span class=\"chip chip--delta chip--{{ .Dir }}\">{{ .Delta }}</span>\n  </p>\n  <div class=\"spark-wrap\">\n    <svg class=\"spark\" viewBox=\"0 0 640 150\" role=\"img\" aria-label=\"Portfolio value trend\">\n      <defs>\n        <linearGradient id=\"sparkFill\" x1=\"0\" y1=\"0\" x2=\"0\" y2=\"1\">\n          <stop offset=\"0%\" stop-color=\"rgba(255,255,255,.45)\"></stop>\n          <stop offset=\"100%\" stop-color=\"rgba(255,255,255,0)\"></stop>\n        </linearGradient>\n      </defs>\n      <path class=\"spark__area\" d=\"{{ .Area }}\" fill=\"url(#sparkFill)\"></path>\n      <polyline class=\"spark__line\" points=\"{{ .Line }}\" fill=\"none\"></polyline>\n      <circle class=\"spark__dot\" cx=\"{{ .DotX }}\" cy=\"{{ .DotY }}\" r=\"4\"></circle>\n    </svg>\n  </div>\n  <p class=\"card__hint\">Server-rendered SVG · redrawn live over SSE.</p>\n</section>"
}
