// Code generated by liquid build; DO NOT EDIT.

package ui

// Template returns the compiled .lsx markup for Counter.
func (c *Counter) Template() string {
	return "<section data-hydro-id=\"{{ .HydroID }}\" id=\"counter\" class=\"card\">\n  <h2>Counter</h2>\n  <p><span id=\"count\">{{ .Count }}</span> clicks</p>\n  <button id=\"increment\" data-liquid-action=\"Increment\">+1</button>\n</section>"
}

// Actions returns the action allowlist compiled from Counter's event
// bindings (D10); the server dispatches only these.
func (c *Counter) Actions() []string {
	return []string{"Increment"}
}
