// Code generated by liquid build; DO NOT EDIT.

package ui

// Template returns the compiled .lsx markup for Dashboard.
func (c *Dashboard) Template() string {
	return "<main class=\"dashboard\">\n  <style>\n    body { font-family: system-ui, sans-serif; margin: 2rem auto; max-width: 40rem; }\n    .card { border: 1px solid #ccc; border-radius: 8px; padding: 1rem; margin: 1rem 0; }\n    .card h2 { margin-top: 0; font-size: 1rem; }\n  </style>\n  <h1>Liquid example dashboard</h1>\n  {{liquidChild \"app-counter\"}}\n  {{liquidChild \"app-metric\" \"reading\" .CurrentRate}}\n  {{liquidChild \"app-stat-card\" \"label\" .StatLabel \"value\" .StatValue}}\n  {{liquidChild \"app-renamer\" \"name\" .BoardName}}\n  <p><a href=\"/admin?key=letmein\">Admin area</a> (guarded — drop the key to get bounced)</p>\n</main>"
}
