// Code generated by liquid build; DO NOT EDIT.

package ui

// Template returns the compiled .lsx markup for Metric.
func (c *Metric) Template() string {
	return "<section data-hydro-id=\"{{ .HydroID }}\" id=\"metric\" class=\"card\" aria-live=\"polite\">\n  <h2>Requests per second</h2>\n  <p><span id=\"reading\">{{ .Reading }}</span> req/s</p>\n</section>"
}
