// Code generated by liquid build; DO NOT EDIT.

package ui

// Template returns the compiled .lsx markup for Renamer.
func (c *Renamer) Template() string {
	return "<section data-hydro-id=\"{{ .HydroID }}\" id=\"renamer\" class=\"card\">\n  <h2>Board name</h2>\n  <p id=\"board-name\">{{ .Name }}</p>\n  <form data-liquid-submit=\"Rename\">\n    <label for=\"new-name\">New name</label>\n    <input id=\"new-name\" name=\"name\" autocomplete=\"off\"/>\n    <button id=\"save\">Save</button>\n  <input type=\"hidden\" name=\"csrf_token\" value=\"{{ .CSRFToken }}\"/></form>\n</section>"
}

// Actions returns the action allowlist compiled from Renamer's event
// bindings (D10); the server dispatches only these.
func (c *Renamer) Actions() []string {
	return []string{"Rename"}
}
