// Code generated by liquid build; DO NOT EDIT.

package ui

// Template returns the compiled .lsx markup for StatCard.
func (c *StatCard) Template() string {
	return "<section data-hydro-id=\"{{ .HydroID }}\" id=\"stat-card\" class=\"card\">\n  <h2>{{ .Label }}</h2>\n  <p id=\"stat-value\">{{ .Value }}</p>\n  {{if .Pinned}}<p id=\"pin-state\">Pinned to the top of your reports.</p>{{end}}\n  <button id=\"pin\" data-liquid-action=\"TogglePin\">Toggle pin</button>\n</section>"
}

// Actions returns the action allowlist compiled from StatCard's event
// bindings (D10); the server dispatches only these.
func (c *StatCard) Actions() []string {
	return []string{"TogglePin"}
}
