// Code generated by liquid build; DO NOT EDIT.

package ui

// Template returns the compiled .lsx markup for Ticker.
func (c *Ticker) Template() string {
	return "<section data-hydro-id=\"{{ .HydroID }}\" id=\"ticker\" class=\"card glass card--wide\">\n  <div class=\"card__head\">\n    <span class=\"card__icon card__icon--ticker\">\n      <svg viewBox=\"0 0 24 24\" fill=\"currentColor\" aria-hidden=\"true\"><path d=\"M3.5 18.5 9 13l4 4 6.5-7.5 1.5 1.4L13 20l-4-4-4 4z\"></path></svg>\n    </span>\n    <h2 class=\"card__title\">Markets</h2>\n    <span class=\"live-dot\" aria-hidden=\"true\"></span>\n  </div>\n  <div class=\"ticker\" role=\"list\" aria-label=\"Live market quotes\">\n    {{range $q := .Quotes}}<div class=\"ticker__item\" role=\"listitem\">\n      <span class=\"ticker__sym\">{{ $q.Symbol }}</span>\n      <span class=\"ticker__px\">{{ $q.Price }}</span>\n      <span class=\"ticker__chg ticker__chg--{{ $q.Dir }}\">{{ $q.Change }}</span>\n    </div>{{end}}\n  </div>\n</section>"
}
