// Code generated by liquid build; DO NOT EDIT.

package ui

// Template returns the compiled .lsx markup for Around.
func (c *Around) Template() string {
	return "<section data-hydro-id=\"{{ .HydroID }}\" id=\"around\" class=\"panel\" aria-live=\"polite\" aria-label=\"Around the league\">\n  <div class=\"panel__head\">\n    <div class=\"panel__title-wrap\">\n      <span class=\"panel__kicker\">Week 5 · Live scores</span>\n      <h2 class=\"panel__title\">Around the League</h2>\n    </div>\n    <span class=\"live-pill\" aria-hidden=\"true\"><span class=\"live-dot\"></span>LIVE</span>\n  </div>\n\n  <div class=\"mini-list\" role=\"list\">\n    {{range $g := .Games}}<div class=\"mini {{ $g.FeaturedClass }}\" role=\"listitem\">\n      <button class=\"mini__row\" data-liquid-action=\"Feature\" data-idx=\"{{ $g.Idx }}\" aria-label=\"Feature this matchup\">\n        <span class=\"mini__side {{ $g.HomeClass }}\">\n          <span class=\"mini__team\">{{ $g.Home }}</span>\n          <span class=\"mini__pts\">{{ $g.HomeScore }}</span>\n        </span>\n        <span class=\"mini__vs\">vs</span>\n        <span class=\"mini__side mini__side--r {{ $g.AwayClass }}\">\n          <span class=\"mini__pts\">{{ $g.AwayScore }}</span>\n          <span class=\"mini__team\">{{ $g.Away }}</span>\n        </span>\n      </button>\n      <div class=\"mini__detail\">\n        <svg class=\"winbar__svg mini__bar\" viewBox=\"0 0 100 8\" preserveAspectRatio=\"none\" role=\"img\" aria-label=\"Home win probability\">\n          <rect class=\"winbar__track\" x=\"0\" y=\"0\" width=\"100\" height=\"8\" rx=\"4\"></rect>\n          <rect class=\"winbar__fill\" x=\"0\" y=\"0\" width=\"{{ $g.WinPct }}\" height=\"8\" rx=\"4\"></rect>\n        </svg>\n        <div class=\"mini__detail-labels\">\n          <span>{{ $g.Home }} <strong>{{ $g.WinPct }}%</strong></span>\n          <span>{{ $g.Away }}</span>\n        </div>\n      </div>\n    </div>{{end}}\n  </div>\n</section>"
}

// Actions returns the action allowlist compiled from Around's event
// bindings (D10); the server dispatches only these.
func (c *Around) Actions() []string {
	return []string{"Feature"}
}
