// Code generated by liquid build; DO NOT EDIT.

package ui

// Template returns the compiled .lsx markup for Around.
func (c *Around) Template() string {
	return "<section data-hydro-id=\"{{ .HydroID }}\" id=\"around\" class=\"panel\" aria-live=\"polite\" aria-label=\"Around the league\">\n  <div class=\"panel__head\">\n    <div class=\"panel__title-wrap\">\n      <span class=\"panel__kicker\">Week 5 · Live scores</span>\n      <h2 class=\"panel__title\">Around the League</h2>\n    </div>\n    <span class=\"live-pill\" aria-hidden=\"true\"><span class=\"live-dot\"></span>LIVE</span>\n  </div>\n\n  <div class=\"mini-list\" role=\"list\">\n    {{range $g := .Games}}<div class=\"mini\" role=\"listitem\">\n      <span class=\"mini__side {{ $g.HomeClass }}\">\n        <span class=\"mini__team\">{{ $g.Home }}</span>\n        <span class=\"mini__pts\">{{ $g.HomeScore }}</span>\n      </span>\n      <span class=\"mini__vs\">vs</span>\n      <span class=\"mini__side mini__side--r {{ $g.AwayClass }}\">\n        <span class=\"mini__pts\">{{ $g.AwayScore }}</span>\n        <span class=\"mini__team\">{{ $g.Away }}</span>\n      </span>\n    </div>{{end}}\n  </div>\n</section>"
}
