// Code generated by liquid build; DO NOT EDIT.

package ui

// Template returns the compiled .lsx markup for Ticker.
func (c *Ticker) Template() string {
	return "<section data-hydro-id=\"{{ .HydroID }}\" id=\"ticker\" class=\"ticker-bar\" aria-live=\"polite\" aria-label=\"Live news and stats\">\n  <span class=\"ticker-bar__brand\" aria-hidden=\"true\"><span class=\"live-dot\"></span>GAMEDAY</span>\n  <div class=\"ticker-bar__rail\" role=\"list\">\n    {{range $i := .Items}}<span class=\"tick tick--{{ $i.KindClass }}\" role=\"listitem\">\n      <span class=\"tick__kind\">{{ $i.Kind }}</span>\n      <span class=\"tick__team\">{{ $i.Team }}</span>\n      <span class=\"tick__text\">{{ $i.Text }}</span>\n    </span>{{end}}\n  </div>\n</section>"
}
