// Code generated by liquid build; DO NOT EDIT.

package ui

// Template returns the compiled .lsx markup for Ticker.
func (c *Ticker) Template() string {
	return "<section data-hydro-id=\"{{ .HydroID }}\" id=\"ticker\" class=\"ticker-bar\" aria-live=\"off\" aria-label=\"Live gameday news and stats\">\n  <span class=\"ticker-bar__brand\" aria-hidden=\"true\"><span class=\"live-dot\"></span>GAMEDAY</span>\n  <div class=\"ticker-bar__rail\">\n    <!-- Two identical copies scroll as one track; translating it -50% loops\n         seamlessly, so the feed streams right-to-left without a visible seam. -->\n    <div class=\"ticker-track\">\n      {{range $i := .Items}}<span class=\"tick tick--{{ $i.KindClass }}\" role=\"listitem\">\n        <span class=\"tick__kind\">{{ $i.Kind }}</span>\n        <span class=\"tick__team\">{{ $i.Team }}</span>\n        <span class=\"tick__text\">{{ $i.Text }}</span>\n      </span>{{end}}\n      {{range $j := .Items}}<span class=\"tick tick--{{ $j.KindClass }}\" aria-hidden=\"true\">\n        <span class=\"tick__kind\">{{ $j.Kind }}</span>\n        <span class=\"tick__team\">{{ $j.Team }}</span>\n        <span class=\"tick__text\">{{ $j.Text }}</span>\n      </span>{{end}}\n    </div>\n  </div>\n</section>"
}
